package com.tamaar.model;// default package
// Generated Jan 17, 2016 1:12:59 PM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "ozuygqof_tamaar")
public class Customer implements java.io.Serializable {

	private Integer customerId;
	private Address address;
	private String title;
	private String firstName;
	private String lastName;
	private String email;
	private String password;
	private String mobileNumber;
	private String landlineNumber;
	private String role;
	private String hdyhau;
	private String enabled;

	private Set<Order> ordersForBillingCustomerId = new HashSet(0);
	private Set<Order> ordersForDeliveryCustomerId = new HashSet(0);
	private Set<Order> ordersForCustomerId = new HashSet(0);

	public Customer() {
	}

	public Customer(Address address, String title, String firstName,
			String lastName, String email, String password,
			String mobileNumber, String landlineNumber, String role, String hdyhau, String enabled,
			Set<Order> ordersForBillingCustomerId, Set<Order> ordersForDeliveryCustomerId,
			Set<Order> ordersForCustomerId) {
		this.address = address;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.mobileNumber = mobileNumber;
		this.landlineNumber = landlineNumber;
		this.role = role;
		this.hdyhau = hdyhau;
		this.ordersForBillingCustomerId = ordersForBillingCustomerId;
		this.ordersForDeliveryCustomerId = ordersForDeliveryCustomerId;
		this.ordersForCustomerId = ordersForCustomerId;
		this.enabled = enabled;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.EAGER,cascade = {CascadeType.ALL})
	@JoinColumn(name = "address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "first_name", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mobile_number", length = 45)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "landline_number", length = 45)
	public String getLandlineNumber() {
		return this.landlineNumber;
	}

	public void setLandlineNumber(String landlineNumber) {
		this.landlineNumber = landlineNumber;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "hdyhau", length = 100)
	public String getHdyhau() {
		return hdyhau;
	}

	public void setHdyhau(String hdyhau) {
		this.hdyhau = hdyhau;
	}

	@Column(name = "enabled", length = 45)
	public String getEnabled() {
		return enabled;
	}

	public void setEnabled(String enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.EAGER, cascade = {CascadeType.ALL}, mappedBy = "customerByBillingCustomerId")
	@JsonIgnore
	public Set<Order> getOrdersForBillingCustomerId() {
		return this.ordersForBillingCustomerId;
	}

	public void setOrdersForBillingCustomerId(Set<Order> ordersForBillingCustomerId) {
		this.ordersForBillingCustomerId = ordersForBillingCustomerId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customerByDeliveryCustomerId")
	@JsonIgnore
	public Set<Order> getOrdersForDeliveryCustomerId() {
		return this.ordersForDeliveryCustomerId;
	}

	public void setOrdersForDeliveryCustomerId(Set<Order> ordersForDeliveryCustomerId) {
		this.ordersForDeliveryCustomerId = ordersForDeliveryCustomerId;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customerByCustomerId")
	@JsonIgnore
	public Set<Order> getOrdersForCustomerId() {
		return this.ordersForCustomerId;
	}

	public void setOrdersForCustomerId(Set<Order> ordersForCustomerId) {
		this.ordersForCustomerId = ordersForCustomerId;
	}


}
