package com.tamaar.model;// default package
// Generated Jan 17, 2016 1:12:59 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ingredient generated by hbm2java
 */
@Entity
@Table(name = "ingredient", catalog = "ozuygqof_tamaar")
public class Ingredient implements java.io.Serializable {

	private int ingredientId;
	private Product product;
	private String key;
	private String value;

	public Ingredient() {
	}

	public Ingredient(int ingredientId) {
		this.ingredientId = ingredientId;
	}

	public Ingredient(int ingredientId, Product product, String key,
			String value) {
		this.ingredientId = ingredientId;
		this.product = product;
		this.key = key;
		this.value = value;
	}

	@Id
	@Column(name = "ingredient_id", unique = true, nullable = false)
	public int getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(int ingredientId) {
		this.ingredientId = ingredientId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "product_id")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "key", length = 50)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
