package com.tamaar.model;// default package
// Generated Jan 27, 2016 7:25:12 AM by Hibernate Tools 3.4.0.CR1

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentDetails generated by hbm2java
 */
@Entity
@Table(name = "payment_details", catalog = "ozuygqof_tamaar")
public class PaymentDetails implements java.io.Serializable {

	private Integer paymentDetailsId;
	private String nameOnCard;
	private String cardType;
	private String cardNumber;
	private String expiryYear;
	private String expiryMonth;
	private String securityNumber;
	//private Set<Order> orders = new HashSet(0);

	public PaymentDetails() {
	}

	public PaymentDetails(String nameOnCard, String cardType,
			String cardNumber, String expiryYear, String expiryMonth,
			String securityNumber, Set orders) {
		this.nameOnCard = nameOnCard;
		this.cardType = cardType;
		this.cardNumber = cardNumber;
		this.expiryYear = expiryYear;
		this.expiryMonth = expiryMonth;
		this.securityNumber = securityNumber;
		//this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "payment_details_id", unique = true, nullable = false)
	public Integer getPaymentDetailsId() {
		return this.paymentDetailsId;
	}

	public void setPaymentDetailsId(Integer paymentDetailsId) {
		this.paymentDetailsId = paymentDetailsId;
	}

	@Column(name = "name_on_card", length = 45)
	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	@Column(name = "card_type", length = 45)
	public String getCardType() {
		return this.cardType;
	}

	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	@Column(name = "card_number", length = 20)
	public String getCardNumber() {
		return this.cardNumber;
	}

	public void setCardNumber(String cardNumber) {
		this.cardNumber = cardNumber;
	}

	@Column(name = "expiry_year", length = 10)
	public String getExpiryYear() {
		return this.expiryYear;
	}

	public void setExpiryYear(String expiryYear) {
		this.expiryYear = expiryYear;
	}

	@Column(name = "expiry_month", length = 10)
	public String getExpiryMonth() {
		return this.expiryMonth;
	}

	public void setExpiryMonth(String expiryMonth) {
		this.expiryMonth = expiryMonth;
	}

	@Column(name = "security_number", length = 5)
	public String getSecurityNumber() {
		return this.securityNumber;
	}

	public void setSecurityNumber(String securityNumber) {
		this.securityNumber = securityNumber;
	}

//	@OneToMany(fetch = FetchType.EAGER, mappedBy = "paymentDetails")
//	@JsonIgnore
//	public Set<Order> getOrders() {
//		return this.orders;
//	}
//
//	public void setOrders(Set<Order> orders) {
//		this.orders = orders;
//	}

}
