// default package
// Generated Jan 17, 2016 1:12:59 PM by Hibernate Tools 3.4.0.CR1
package com.tamaar.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.tamaar.model.Price;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "ozuygqof_tamaar")
public class Product implements java.io.Serializable {

	private String productId;
	private Price price;
	private String description;
	private String available;
	private String imagePath;
	private BigDecimal size;

	private Set<OrderDetail> orderDetails = new HashSet(0);
	private Set<Ingredient> ingredients = new HashSet(0);
	private Set<Howtouse> howtouses = new HashSet(0);

	public Product() {
	}

	public Product(String productId, String description, String available, BigDecimal size) {
		this.productId = productId;
		this.description = description;
		this.available = available;
		this.size = size;
	}

	public Product(String productId, Price price, String description,
			String available, String imagePath, Set orderDetails,
			Set ingredients, Set howtouses) {
		this.productId = productId;
		this.price = price;
		this.description = description;
		this.available = available;
		this.imagePath = imagePath;
		this.orderDetails = orderDetails;
		this.ingredients = ingredients;
		this.howtouses = howtouses;
	}

	@Id
	@Column(name = "product_id", unique = true, nullable = false, length = 100)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "price_id")
	public Price getPrice() {
		return this.price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "available", nullable = false, length = 1)
	public String getAvailable() {
		return this.available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

	@Column(name = "image_path", length = 200)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "product")
	@JsonIgnore
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "product")
	@JsonIgnore
	public Set<Ingredient> getIngredients() {
		return this.ingredients;
	}

	public void setIngredients(Set<Ingredient> ingredients) {
		this.ingredients = ingredients;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "product")
	@JsonIgnore
	public Set<Howtouse> getHowtouses() {
		return this.howtouses;
	}

	public void setHowtouses(Set<Howtouse> howtouses) {
		this.howtouses = howtouses;
	}

	@Column(name = "size", precision = 5)
	public BigDecimal getSize() {
		return size;
	}

	public void setSize(BigDecimal size) {
		this.size = size;
	}
}
