// default package
// Generated Jan 17, 2016 1:12:59 PM by Hibernate Tools 3.4.0.CR1
package com.tamaar.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "ozuygqof_tamaar")
public class Project implements java.io.Serializable {

	private String projectId;

	public Project() {
	}

	public Project(String projectId) {
		this.projectId = projectId;
	}

	@Id
	@Column(name = "project_id", unique = true, nullable = false, length = 45)
	public String getProjectId() {
		return this.projectId;
	}

	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

}
