package com.tamaar.model;// default package
// Generated Jan 17, 2016 1:12:59 PM by Hibernate Tools 3.4.0.CR1



import com.fasterxml.jackson.annotation.JsonIgnore;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shipper generated by hbm2java
 */
@Entity
@Table(name = "shipper", catalog = "ozuygqof_tamaar")
public class Shipper implements java.io.Serializable {

	private String shipperId;
	private String name;
	private BigDecimal price;
	private Set<Order> orders = new HashSet(0);

	public Shipper() {
	}

	public Shipper(String shipperId) {
		this.shipperId = shipperId;
	}

	public Shipper(String shipperId, String name, BigDecimal price, Set orders) {
		this.shipperId = shipperId;
		this.name = name;
		this.price = price;
		this.orders = orders;
	}

	@Id
	@Column(name = "shipper_id", unique = true, nullable = false, length = 100)
	public String getShipperId() {
		return this.shipperId;
	}

	public void setShipperId(String shipperId) {
		this.shipperId = shipperId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 5)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "shipper")
	@JsonIgnore
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
