// default package
// Generated Jan 17, 2016 1:12:59 PM by Hibernate Tools 3.4.0.CR1
package com.tamaar.model;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", catalog = "ozuygqof_tamaar")
public class UserProfile implements java.io.Serializable {

	private int userId;
	private Address address;
	private String firstName;
	private String middleName;
	private String lastName;
	private String email;
	private String password;
	private String whereYouHearAboutUs;
	private String mobileNumber;
	private String landlineNumber;

	public UserProfile() {
	}

	public UserProfile(int userId, Address address, String firstName,
			String lastName, String email, String password, String mobileNumber) {
		this.userId = userId;
		this.address = address;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.mobileNumber = mobileNumber;
	}

	public UserProfile(int userId, Address address, String firstName,
			String middleName, String lastName, String email, String password,
			String whereYouHearAboutUs, String mobileNumber,
			String landlineNumber) {
		this.userId = userId;
		this.address = address;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
		this.whereYouHearAboutUs = whereYouHearAboutUs;
		this.mobileNumber = mobileNumber;
		this.landlineNumber = landlineNumber;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "where_you_hear_about_us", length = 45)
	public String getWhereYouHearAboutUs() {
		return this.whereYouHearAboutUs;
	}

	public void setWhereYouHearAboutUs(String whereYouHearAboutUs) {
		this.whereYouHearAboutUs = whereYouHearAboutUs;
	}

	@Column(name = "mobile_number", nullable = false, length = 45)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "landline_number", length = 45)
	public String getLandlineNumber() {
		return this.landlineNumber;
	}

	public void setLandlineNumber(String landlineNumber) {
		this.landlineNumber = landlineNumber;
	}

}
